M:\Projects\Duru_ZeytinyagliReplace_McCann_190617\*.* > J:\_M_BACKUP\Projects\Duru_ZeytinyagliReplace_McCann_190617 /us
M:\Projects\Derby_Samurai_Model_dd_190619\*.* > J:\_M_BACKUP\Projects\Derby_Samurai_Model_dd_190619 /us
M:\Projects\StrangerThings_Saadettin_Teksoy_Netflix_190624\*.* > J:\_M_BACKUP\Projects\StrangerThings_Saadettin_Teksoy_Netflix_190624 /us
M:\Projects\CocaCola_Maximum_Ptot_190704\*.* > J:\_M_BACKUP\Projects\CocaCola_Maximum_Ptot_190704 /us
M:\Projects\Balparmak_Ari_Imaj_190705\*.* > J:\_M_BACKUP\Projects\Balparmak_Ari_Imaj_190705 /us
M:\Projects\Colins_Statue_Depo_190717\*.* > J:\_M_BACKUP\Projects\Colins_Statue_Depo_190717 /us
M:\Projects\Eti_GofretDemo_GS_190718\*.* > J:\_M_BACKUP\Projects\Eti_GofretDemo_GS_190718 /us
M:\Projects\Fox_TanitimFilmi_Balonlar_Depo_190723\*.* > J:\_M_BACKUP\Projects\Fox_TanitimFilmi_Balonlar_Depo_190723 /us
M:\Projects\Molped_Afrika_happypeople_190731\*.* > J:\_M_BACKUP\Projects\Molped_Afrika_happypeople_190731 /us
M:\Projects\_ResearchAndDev_____190801\*.* > J:\_M_BACKUP\Projects\_ResearchAndDev_____190801 /us
M:\Projects\Knorr_Domatesler_Lowe_190802\*.* > J:\_M_BACKUP\Projects\Knorr_Domatesler_Lowe_190802 /us
M:\Projects\Marc_CamasirMakinasiTemizleyicisi_RB_190820\*.* > J:\_M_BACKUP\Projects\Marc_CamasirMakinasiTemizleyicisi_RB_190820 /us
M:\Projects\Evy_Baby_BebekBeziDemo_Shortcut_190821\*.* > J:\_M_BACKUP\Projects\Evy_Baby_BebekBeziDemo_Shortcut_190821 /us
M:\Projects\Fakir_ElektrikSupurgeDemo_25Film_190821\*.* > J:\_M_BACKUP\Projects\Fakir_ElektrikSupurgeDemo_25Film_190821 /us
M:\Projects\ETI_HOSBES_imajstudio_190827\*.* > J:\_M_BACKUP\Projects\ETI_HOSBES_imajstudio_190827 /us
M:\Projects\Eti_Canga_Rafineri_190828\*.* > J:\_M_BACKUP\Projects\Eti_Canga_Rafineri_190828 /us
M:\Projects\Coca_Cola_Q3_promo_OGILVY_190830\*.* > J:\_M_BACKUP\Projects\Coca_Cola_Q3_promo_OGILVY_190830 /us
M:\Projects\BayiToplantisi___BKM_190911\*.* > J:\_M_BACKUP\Projects\BayiToplantisi___BKM_190911 /us
M:\Projects\Ulker_8KekPS_PTOT_190930\*.* > J:\_M_BACKUP\Projects\Ulker_8KekPS_PTOT_190930 /us
M:\Projects\Jumbo_BTS_Shortcut_191003\*.* > J:\_M_BACKUP\Projects\Jumbo_BTS_Shortcut_191003 /us
M:\Projects\Kelebek_logoKelebekler_DEPO_191003\*.* > J:\_M_BACKUP\Projects\Kelebek_logoKelebekler_DEPO_191003 /us
M:\Projects\Samsung_render\*.* > J:\_M_BACKUP\Projects\Samsung_render /us
M:\Projects\Nulook_EltilerinSavasi_Netflix_191104\*.* > J:\_M_BACKUP\Projects\Nulook_EltilerinSavasi_Netflix_191104 /us
M:\Projects\NarutoSasuke\*.* > J:\_M_BACKUP\Projects\NarutoSasuke /us
M:\Projects\ETI_BALIK_KRAKER_Sebzeli_GS_191107\*.* > J:\_M_BACKUP\Projects\ETI_BALIK_KRAKER_Sebzeli_GS_191107 /us
M:\Projects\_transfer\*.* > J:\_M_BACKUP\Projects\_transfer /us
M:\Projects\Eti_AhenkGurme_Replacement_GS_191111\*.* > J:\_M_BACKUP\Projects\Eti_AhenkGurme_Replacement_GS_191111 /us
M:\Projects\Sutas_Buzu_Acilis_HappyPeople_191112\*.* > J:\_M_BACKUP\Projects\Sutas_Buzu_Acilis_HappyPeople_191112 /us
M:\Projects\smDatabase\*.* > J:\_M_BACKUP\Projects\smDatabase /us
M:\Projects\scenes\*.* > J:\_M_BACKUP\Projects\scenes /us
M:\Projects\Playblasts\*.* > J:\_M_BACKUP\Projects\Playblasts /us
M:\Projects\ats_AskTesadufleriSever2_Bocek_191115\*.* > J:\_M_BACKUP\Projects\ats_AskTesadufleriSever2_Bocek_191115 /us
M:\Projects\Sutas_TatlimPaket_HappyPeople_191203\*.* > J:\_M_BACKUP\Projects\Sutas_TatlimPaket_HappyPeople_191203 /us
M:\Projects\Ulker_DidoPaketler_Ptot_191204\*.* > J:\_M_BACKUP\Projects\Ulker_DidoPaketler_Ptot_191204 /us
